### ISSUE TITLE
落し物を検索するボタン

### ISSUE THREAD

**Issue by prpr-man** [shopetan/LPM#12]
このボタンに句点「．」がついてますが，ボタンに句点があるのは変な気がするので直したほうがいいでしょうか？
あと，Webページ全体の句読点が「，．」になっているので「、。」に直したほうが自然かもしれません．(たいていのWebページはそうなっている気がするので)

**Comment by shopetan** [comment]
ああwwwwごめんなさいwwww 
お願いします．

**Comment by prpr-man** [comment]
かしこまっ!

**Comment by shopetan** [comment]
修正して一段落したらプルリクお願いします． 確認して無事にMergeしたらこのIssueは閉じますね．

**Comment by prpr-man** [comment]
了解です(テスト終わらなければ一段落できそうにないですが…)
