### ISSUE TITLE
同じユーザーであってもtwitter，facebookでログインされるとID情報が異なり別のユーザーとして判断されてしまうかも問題

### ISSUE THREAD

**Issue by prpr-man** [shopetan/LPM#16]
タイトル通りです．
twitterとfacebookのIDをひもづけるデータベースが必要になるかもしれません．

**Comment by shopetan** [comment]
twitterとFacebookでログイン時に情報が変わるってことですよね．
一般的なユーザ認証もそれは同じだったはずなので，どのアカウントでログインしてたかという話はユーザ個人に任せたほうが良い気がしました．

**Comment by prpr-man** [comment]
よく考えたら，システム側からひもづけるにはユーザーに設定してもらうしかないですね．
これはなしということで．

**Comment by shopetan** [comment]
大丈夫そうなのでcloseしておきます! thx :) :+1:
