### ISSUE TITLE
milkccaにデータを送る際に正しくデータをストア出来ない件

### ISSUE THREAD

**Issue by shopetan** [shopetan/LPM#20]
https://github.com/shopetan/LPM/blob/46673119bc91963f9d4309a1511ebf614dda3811/js/create.js

``` javascript
var milkcocoa = new MilkCocoa("noteibxtd2w3.mlkcca.com");
var lpmDataStore = milkcocoa.dataStore("LostProperty");
var name,category,imagePath,pickUpLatitude,pickUpLongitude,pickUpAddress;


function clickEvent(){
    name = document.getElementById("nameArea");
    category = document.getElementById("selectArea");
    imagePath = document.getElementById("fileInput");
    pickUpLatitude = document.getElementById("id_lat");
    pickUpLongitude = document.getElementById("id_lng");
    pickUpAddress = document.getElementById("id_address");

    console.log(name);
    sendData(name.value,category.value,imagePath.value,pickUpLatitude.value,pickUpLongitude.value,pickUpAddress.value);
}
function sendData(name,category,imagePath,pickUpLatitude,pickUpLongitude,pickUpAddress){
    lpmDataStore.push({
        name:name,
        category:category,
        imagePath:imagePath,
        pickUpLatitude:pickUpLatitude,
        pickUpLongitude:pickUpLongitude,
        pickUpAddress:pickUpAddress
    });
    name = "";
    category = "";
    imagePath = "";
    pickUpLatitude = "";
    pickUpLongitude = "";
    pickUpAddress = "";
}
```

こんな感じでデータを送ろうとしているのですが，
名前欄に何か入力した場合は[object HTMLInputElement]が入り，
何も入力しない場合はnullのストアすらされません．
また，位置情報なども同様にストアされません．

![参考画像](http://uploader.sakura.ne.jp/src/up146228.png)
何がマズイかご指摘願います．

**Comment by prpr-man** [comment]
セキュリティルールとかはどうなってますか？

**Comment by momenneko** [comment]
sendData関数の中で console.log(name) とするとどうなりますか？

グローバル変数として宣言されている name,category,...が、sendData関数の引数と同じ名前なのが原因かも？
つまりデータストアに push されたのは、関数の引数ではない方のグローバル変数name,category,... ( name = document.getElementById("nameArea"); などのオブジェクト)かもしれません(間違っていたらすみません)。

**Comment by shopetan** [comment]
@prpr-man 

```
* {
    permit : all;
    rule : true;
}
```

こんなかんじです． デフォルトから変更はしてないです．

@momenneko 
グローバル変数の宣言をやめて，関数内のローカル変数に置き換えたところうまくいきました．
ただ，現在住所等の動的に拾ってきたidのデータは上手く言ってない状態です…．

変更時のコミットログです．
https://github.com/shopetan/LPM/commit/9790dcbc41aee2316c6e577977c873e64557a88e

**Comment by momenneko** [comment]
住所等のデータは div 要素なので、pickUpAddress.value のところを pickUpAddress.innerHTML にすれば拾えると思います.

**Comment by shopetan** [comment]
無事に正しくデータを取得することができました! thx :+1:
