### ISSUE TITLE
画像をサーバー上に保存をどうするか問題

### ISSUE THREAD

**Issue by prpr-man** [shopetan/LPM#21]
ユーザーのプロフィールページのアイコンとか，落し物の画像とかのアップロードですが，javascriptだとできない(と思う)のでphpとか書かないとダメっぽいです．

**Comment by momenneko** [comment]
そうみたいですね...(php書けない勢)

**Comment by prpr-man** [comment]
php書いて何とかしました…

**Comment by shopetan** [comment]
今週僕の画像uploadも対応願います😊

**Comment by momenneko** [comment]
ありがとうございます :bow:
