### ISSUE TITLE
スマホ版でログイン後のドロップダウンメニューが隠れてしまう問題

### ISSUE THREAD

**Issue by prpr-man** [shopetan/LPM#30]
表題の通りです．Bootstrapの当て方がまずいんでしょうか？

**Comment by shopetan** [comment]
Google ChromeのDev機能を用いて確認していますが，ログイン後にもドロップダウンメニュー(ハンバーガーボタンという認識であっているかな?) は正常に機能しているように感じました．
具体的にどういう状態になるのかスクリーンショット等で報告して頂けませんか?

追記
ログイン後にログアウトをし，再びログインを試みると… 
という感じで確認したら認証ページがズレちゃってましたが，これはリダイレクト先が本番環境だったからでした．
@prpr-man が指しているのはこの現象ですか? (おそらく違うと思いますが…)

**Comment by prpr-man** [comment]
![2015-07-21 21 36 16](https://cloud.githubusercontent.com/assets/6441844/8800793/9dc1b1b0-2ff0-11e5-94c7-c467645efa60.png)

この画像中のドロップダウンメニュー(Logoutが表示されている)です．本来ならばLogoutの下にProfileが表示されているはずですが，途切れて見えないという状態です．

**Comment by momenneko** [comment]
確かにそうなりますね...
隠れる理由はわかりませんが、
.open 状態の dropdown-menu クラスの position を absolute から relative に変更すると隠れなくなるのでこれで対処できるかも?

**Comment by prpr-man** [comment]
@momenneko ありがとうございます．その対処法でやってみたところ上手くいきました．
