### ISSUE TITLE
検索システム作成中

### ISSUE THREAD

**Issue by momenneko** [shopetan/LPM#8]
# 今日出来たこと
1. 入力されたキーワードを含む名前を( milkcocoa から)検索する
2.  住所、カテゴリを完全一致で検索する(プルリクしたコードではコメントアウト中)
# TODO
1. 名前、住所、カテゴリを AND 検索する
2. 検索結果をリストからテーブルに変更する
3. honoka でカッコイイ感じにする

**Comment by shopetan** [comment]
このへんは達成出来てそうですね! 
closeしておきます! thx :)
